version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run: pwd
      - run: ls

      - run:
          name: ライセンスの同意
          command: yes | sdkmanager --licenses || exit 0

      - run:
          name: デバッグAPKのビルド
          command: cd androidApp;sudo chmod +x gradlew;./gradlew assembleDebug

      - run:
          name: unit test
          command: cd androidApp;sudo chmod +x gradlew;./gradlew test
