version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run:
          name: デバッグAPKのビルド
          command: ./gradlew assembleDebug
