version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run:
          name: デバッグAPKのビルド
          command: cd androidApp;sudo chmod +x gradlew;./gradlew assembleDebug
